targets:
  $default:
    sources:
      - "lib/**"
      - "bin/**"
      - "test/**"
      - "pubspec.yaml"
      - "$package$"
    builders:
      json_serializable:
        generate_for:
          - "lib/**"
      freezed:
        generate_for:
          - "lib/**"
      l10n_mapper_generator:
        generate_for:
          - "lib/**"