import 'package:dr_copilot/src/features/financials/data/remote/abstract_financial_api.dart';
import 'package:dr_copilot/src/features/financials/transactions/domain/models/transaction_model.dart';
import 'package:dr_copilot/src/features/appointments/sessions/domain/usecases/sessions_usecase.dart';
import 'package:dr_copilot/src/features/appointments/evaluations/domain/usecases/evaluations_usecase.dart';
import 'package:dartz/dartz.dart';
import 'package:dr_copilot/src/core/error/failures.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:dr_copilot/src/features/financials/domain/models/currency_profile_model.dart';
import 'package:flutter/material.dart';

/// Handles Firebase operations for financial transactions.
class FinancialsFirebaseApi extends AbstractFinancialApi {
  final SessionsUseCase sessionsUseCase;
  final EvaluationsUseCase evaluationsUseCase;

  FinancialsFirebaseApi({
    required this.sessionsUseCase,
    required this.evaluationsUseCase,
  });

  @override
  Future<TransactionModel> addFinancial(TransactionModel financial) {
    // TODO: implement addFinancial
    throw UnimplementedError();
  }

  @override
  Future<void> deleteFinancial(String financialId) {
    // TODO: implement deleteFinancial
    throw UnimplementedError();
  }

  /// Gets all transactions (financial records).
  @override
  Future<List<TransactionModel>> fetchFinancials() {
    // TODO: implement fetchFinancials
    throw UnimplementedError();
  }

  @override
  Future<TransactionModel> updateFinancial(TransactionModel financial) {
    // TODO: implement updateFinancial
    throw UnimplementedError();
  }

  /// Gets the sum of session costs for a given month and year.
  Future<Either<Failure, double>> getSessionsSumForMonth(
      {required int year, required int month}) {
    return sessionsUseCase.sumSessionCostsForMonth(year: year, month: month);
  }

  /// Gets the sum of session costs for a given year.
  Future<Either<Failure, double>> getSessionsSumForYear({required int year}) {
    return sessionsUseCase.sumSessionCostsForYear(year: year);
  }

  /// Gets the sum of evaluation costs for a given month and year.
  Future<Either<Failure, double>> getEvaluationsSumForMonth(
      {required int year, required int month}) {
    return evaluationsUseCase.sumEvaluationCostsForMonth(
        year: year, month: month);
  }

  /// Gets the sum of evaluation costs for a given year.
  Future<Either<Failure, double>> getEvaluationsSumForYear(
      {required int year}) {
    return evaluationsUseCase.sumEvaluationCostsForYear(year: year);
  }

  /// Gets the count of sessions.
  Future<Either<Failure, int>> getSessionsCount() {
    return sessionsUseCase.getSessionsCount();
  }

  /// Gets the count of sessions for a specific month and year.
  Future<Either<Failure, int>> getSessionsCountForMonth(
      {required int year, required int month}) {
    return sessionsUseCase.getSessionsCountForMonth(year: year, month: month);
  }

  /// Gets the count of sessions for a specific year.
  Future<Either<Failure, int>> getSessionsCountForYear({required int year}) {
    return sessionsUseCase.getSessionsCountForYear(year: year);
  }

  /// Gets the count of evaluations.
  Future<Either<Failure, int>> getEvaluationsCount() async {
    return await evaluationsUseCase.repository.getEvaluationsCount();
  }

  /// Gets the count of evaluations for a specific month and year.
  Future<Either<Failure, int>> getEvaluationsCountForMonth(
      {required int year, required int month}) {
    return evaluationsUseCase.getEvaluationsCountForMonth(
        year: year, month: month);
  }

  /// Gets the count of evaluations for a specific year.
  Future<Either<Failure, int>> getEvaluationsCountForYear({required int year}) {
    return evaluationsUseCase.getEvaluationsCountForYear(year: year);
  }

  /// Adds a new currency profile to the user's currency_profiles subcollection in Firestore.
  /// The document ID will be generated by Firestore and set as the model's id.
  Future<Either<Failure, CurrencyProfileModel>> addCurrencyProfile({
    required CurrencyProfileModel currencyProfile,
  }) async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        final data = currencyProfile.toJson();
        final docRef = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('currency_profiles')
            .add(data);
        final newProfile = currencyProfile.copyWith(id: docRef.id);
        return Right(newProfile);
      }
      return Left(ServerFailure('User not authenticated', 401));
    } catch (e) {
      debugPrint('Error adding currency profile: $e');
      return Left(ServerFailure(e.toString(), 500));
    }
  }

  /// Fetches all currency profiles for the current user.
  @override
  Future<Either<Failure, List<CurrencyProfileModel>>>
      fetchCurrencyProfiles() async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        final snapshot = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('currency_profiles')
            .get();
        final profiles = snapshot.docs
            .map((doc) => CurrencyProfileModel.fromJson({...doc.data()}))
            .toList();
        return Right(profiles);
      }
      return Left(ServerFailure('User not authenticated', 401));
    } catch (e) {
      debugPrint('Error fetching currency profiles: $e');
      return Left(ServerFailure(e.toString(), 500));
    }
  }

  /// Deletes a currency profile by its document ID for the current user.
  @override
  Future<Either<Failure, void>> deleteCurrencyProfile(String id) async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('currency_profiles')
            .doc(id)
            .delete();
        return const Right(null);
      }
      return Left(ServerFailure('User not authenticated', 401));
    } catch (e) {
      debugPrint('Error deleting currency profile: $e');
      return Left(ServerFailure(e.toString(), 500));
    }
  }

  /// Updates an existing currency profile for the current user.
  @override
  Future<Either<Failure, CurrencyProfileModel>> updateCurrencyProfile(
      CurrencyProfileModel profile) async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('currency_profiles')
            .doc(profile.id)
            .update(profile.toJson());
        return Right(profile);
      }
      return Left(ServerFailure('User not authenticated', 401));
    } catch (e) {
      debugPrint('Error updating currency profile: $e');
      return Left(ServerFailure(e.toString(), 500));
    }
  }
}
