// Mocks generated by Mockito 5.4.5 from annotations
// in dr_copilot/test/src/features/appointments/sessions/domain/usecases/sessions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dr_copilot/src/core/error/failures.dart' as _i5;
import 'package:dr_copilot/src/features/appointments/sessions/domain/models/session_model.dart'
    as _i6;
import 'package:dr_copilot/src/features/appointments/sessions/domain/repositories/abstract_sessions_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [AbstractSessionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractSessionsRepository extends _i1.Mock
    implements _i3.AbstractSessionsRepository {
  MockAbstractSessionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>> getSessions({
    String? lastDocumentID,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getSessions, [], {
          #lastDocumentID: lastDocumentID,
          #limit: limit,
        }),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>.value(
          _FakeEither_0<_i5.Failure, List<_i6.SessionModel>>(
            this,
            Invocation.method(#getSessions, [], {
              #lastDocumentID: lastDocumentID,
              #limit: limit,
            }),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>> addSession(
    _i6.SessionModel? sessionModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#addSession, [sessionModel]),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>>.value(
          _FakeEither_0<_i5.Failure, _i6.SessionModel>(
            this,
            Invocation.method(#addSession, [sessionModel]),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>> updateSession(
    String? id,
    _i6.SessionModel? sessionModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateSession, [id, sessionModel]),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>>.value(
          _FakeEither_0<_i5.Failure, _i6.SessionModel>(
            this,
            Invocation.method(#updateSession, [id, sessionModel]),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSession(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#deleteSession, [id]),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
          _FakeEither_0<_i5.Failure, void>(
            this,
            Invocation.method(#deleteSession, [id]),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>> searchSessions({
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#searchSessions, [], {#name: name}),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>.value(
          _FakeEither_0<_i5.Failure, List<_i6.SessionModel>>(
            this,
            Invocation.method(#searchSessions, [], {#name: name}),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>> getSessionsByDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getSessionsByDate, [date]),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>.value(
          _FakeEither_0<_i5.Failure, List<_i6.SessionModel>>(
            this,
            Invocation.method(#getSessionsByDate, [date]),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SessionType>> detectSessionType(
    String? patientId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#detectSessionType, [patientId]),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.SessionType>>.value(
          _FakeEither_0<_i5.Failure, _i6.SessionType>(
            this,
            Invocation.method(#detectSessionType, [patientId]),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SessionType>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getSessionsCount() =>
      (super.noSuchMethod(
        Invocation.method(#getSessionsCount, []),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
          _FakeEither_0<_i5.Failure, int>(
            this,
            Invocation.method(#getSessionsCount, []),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getSessionsCountForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getSessionsCountForMonth, [], {
          #year: year,
          #month: month,
        }),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
          _FakeEither_0<_i5.Failure, int>(
            this,
            Invocation.method(#getSessionsCountForMonth, [], {
              #year: year,
              #month: month,
            }),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getSessionsCountForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getSessionsCountForYear, [], {#year: year}),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
          _FakeEither_0<_i5.Failure, int>(
            this,
            Invocation.method(#getSessionsCountForYear, [], {#year: year}),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> sumSessionCostsForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#sumSessionCostsForMonth, [], {
          #year: year,
          #month: month,
        }),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
          _FakeEither_0<_i5.Failure, double>(
            this,
            Invocation.method(#sumSessionCostsForMonth, [], {
              #year: year,
              #month: month,
            }),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> sumSessionCostsForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#sumSessionCostsForYear, [], {#year: year}),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
          _FakeEither_0<_i5.Failure, double>(
            this,
            Invocation.method(#sumSessionCostsForYear, [], {#year: year}),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> sumAllSessionCostsForUser() =>
      (super.noSuchMethod(
        Invocation.method(#sumAllSessionCostsForUser, []),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
          _FakeEither_0<_i5.Failure, double>(
            this,
            Invocation.method(#sumAllSessionCostsForUser, []),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);
}
