// Mocks generated by Mockito 5.4.6 from annotations
// in dr_copilot/test/unit/blocs/copilot_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i7;

import 'package:dr_copilot/src/features/copilot_chat/domain/services/ai_service_interface.dart'
    as _i2;
import 'package:dr_copilot/src/features/copilot_chat/services/ai_router_service.dart'
    as _i14;
import 'package:dr_copilot/src/features/copilot_chat/services/claude_service.dart'
    as _i13;
import 'package:dr_copilot/src/features/copilot_chat/services/deepseek_service.dart'
    as _i11;
import 'package:dr_copilot/src/features/copilot_chat/services/gemini_service.dart'
    as _i9;
import 'package:dr_copilot/src/features/copilot_chat/services/gpt_service.dart'
    as _i8;
import 'package:dr_copilot/src/features/copilot_chat/services/qwen_service.dart'
    as _i12;
import 'package:dr_copilot/src/features/copilot_chat/services/vertex_ai_service.dart'
    as _i4;
import 'package:flutter/foundation.dart' as _i15;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:google_generative_ai/google_generative_ai.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAIService_0 extends _i1.SmartFake implements _i2.AIService {
  _FakeAIService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_1 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_2 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_3 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_4 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_5 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppleOptions_6 extends _i1.SmartFake implements _i3.AppleOptions {
  _FakeAppleOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VertexAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVertexAIService extends _i1.Mock implements _i4.VertexAIService {
  MockVertexAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> getMedPaLMResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedPaLMResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getMedPaLMResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getMedPaLMResponseFromBytes(
    _i7.Uint8List? fileBytes, {
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedPaLMResponseFromBytes,
          [fileBytes],
          {
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getMedPaLMResponseFromBytes,
            [fileBytes],
            {
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [GPTService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGPTService extends _i1.Mock implements _i8.GPTService {
  MockGPTService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> getGPTResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGPTResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getGPTResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i9.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i10.GenerateContentResponse> getGeminiResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGeminiResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<_i10.GenerateContentResponse>.value(
            _i5.dummyValue<_i10.GenerateContentResponse>(
          this,
          Invocation.method(
            #getGeminiResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<_i10.GenerateContentResponse>);
}

/// A class which mocks [DeepSeekService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepSeekService extends _i1.Mock implements _i11.DeepSeekService {
  MockDeepSeekService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> getDeepSeekResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeepSeekResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDeepSeekResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getDeepSeekResponseFromBytes(
    _i7.Uint8List? fileBytes, {
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeepSeekResponseFromBytes,
          [fileBytes],
          {
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDeepSeekResponseFromBytes,
            [fileBytes],
            {
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [QwenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQwenService extends _i1.Mock implements _i12.QwenService {
  MockQwenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> getQwenResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQwenResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getQwenResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getQwenResponseFromBytes(
    _i7.Uint8List? fileBytes, {
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQwenResponseFromBytes,
          [fileBytes],
          {
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getQwenResponseFromBytes,
            [fileBytes],
            {
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [ClaudeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClaudeService extends _i1.Mock implements _i13.ClaudeService {
  MockClaudeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i6.Future<String> generateResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponseWithImage(
    String? query,
    _i7.Uint8List? imageBytes, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithImage,
          [
            query,
            imageBytes,
          ],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithImage,
            [
              query,
              imageBytes,
            ],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  void updateModelConfig(List<String>? requiredFields) => super.noSuchMethod(
        Invocation.method(
          #updateModelConfig,
          [requiredFields],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> getClaudeResponse(
    String? query, {
    List<Map<String, dynamic>>? messageHistory = const [],
    String? clinicId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClaudeResponse,
          [query],
          {
            #messageHistory: messageHistory,
            #clinicId: clinicId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getClaudeResponse,
            [query],
            {
              #messageHistory: messageHistory,
              #clinicId: clinicId,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getClaudeResponseFromBytes(_i7.Uint8List? fileBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClaudeResponseFromBytes,
          [fileBytes],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getClaudeResponseFromBytes,
            [fileBytes],
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [AIRouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIRouterService extends _i1.Mock implements _i14.AIRouterService {
  MockAIRouterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AIService> getServiceForQuery({
    required String? query,
    required String? clinicId,
    bool? forcePremium = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceForQuery,
          [],
          {
            #query: query,
            #clinicId: clinicId,
            #forcePremium: forcePremium,
          },
        ),
        returnValue: _i6.Future<_i2.AIService>.value(_FakeAIService_0(
          this,
          Invocation.method(
            #getServiceForQuery,
            [],
            {
              #query: query,
              #clinicId: clinicId,
              #forcePremium: forcePremium,
            },
          ),
        )),
      ) as _i6.Future<_i2.AIService>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_1(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_2(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_3(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_4(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_5(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i3.WebOptions);

  @override
  _i3.AppleOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeAppleOptions_6(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i3.AppleOptions);

  @override
  Map<String, List<_i15.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
        Invocation.getter(#getListeners),
        returnValue: <String, List<_i15.ValueChanged<String?>>>{},
      ) as Map<String, List<_i15.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> write({
    required String? key,
    required String? value,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> read({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> containsKey({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> delete({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String>> readAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> deleteAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);
}
