// Mocks generated by Mockito 5.4.5 from annotations
// in dr_copilot/test/src/features/ai_voice_assistant/domain/services/command_parser_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i14;
import 'package:dartz/dartz.dart' as _i4;
import 'package:dr_copilot/src/core/error/failures.dart' as _i12;
import 'package:dr_copilot/src/features/copilot/services/gemini_service.dart'
    as _i2;
import 'package:dr_copilot/src/features/patients/domain/models/patient_model.dart'
    as _i13;
import 'package:dr_copilot/src/features/patients/domain/repositories/abstract_patients_repository.dart'
    as _i3;
import 'package:dr_copilot/src/features/patients/domain/usecases/patients_usecase.dart'
    as _i11;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i6;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGeminiResponse_0 extends _i1.SmartFake
    implements _i2.GeminiResponse {
  _FakeGeminiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbstractPatientsRepository_1 extends _i1.SmartFake
    implements _i3.AbstractPatientsRepository {
  _FakeAbstractPatientsRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_4 extends _i1.SmartFake
    implements _i6.ActionCodeInfo {
  _FakeActionCodeInfo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_5 extends _i1.SmartFake
    implements _i7.UserCredential {
  _FakeUserCredential_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_6 extends _i1.SmartFake
    implements _i7.ConfirmationResult {
  _FakeConfirmationResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_7 extends _i1.SmartFake implements _i6.UserMetadata {
  _FakeUserMetadata_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_8 extends _i1.SmartFake implements _i7.MultiFactor {
  _FakeMultiFactor_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_9 extends _i1.SmartFake implements _i6.IdTokenResult {
  _FakeIdTokenResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_10 extends _i1.SmartFake implements _i7.User {
  _FakeUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i2.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i9.Future<_i2.GeminiResponse> getGeminiResponse(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getGeminiResponse, [query]),
            returnValue: _i9.Future<_i2.GeminiResponse>.value(
              _FakeGeminiResponse_0(
                this,
                Invocation.method(#getGeminiResponse, [query]),
              ),
            ),
          )
          as _i9.Future<_i2.GeminiResponse>);

  @override
  _i9.Future<_i2.GeminiResponse> getGeminiResponseFromBytes(
    _i10.Uint8List? fileBytes,
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGeminiResponseFromBytes, [fileBytes, text]),
            returnValue: _i9.Future<_i2.GeminiResponse>.value(
              _FakeGeminiResponse_0(
                this,
                Invocation.method(#getGeminiResponseFromBytes, [
                  fileBytes,
                  text,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.GeminiResponse>);
}

/// A class which mocks [PatientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientsUseCase extends _i1.Mock implements _i11.PatientsUseCase {
  MockPatientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AbstractPatientsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbstractPatientsRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AbstractPatientsRepository);

  @override
  _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>> getPatients({
    required String? lastDocumentId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPatients, [], {
              #lastDocumentId: lastDocumentId,
              #limit: limit,
            }),
            returnValue: _i9.Future<
              _i4.Either<_i12.Failure, List<_i13.PatientModel>>
            >.value(
              _FakeEither_2<_i12.Failure, List<_i13.PatientModel>>(
                this,
                Invocation.method(#getPatients, [], {
                  #lastDocumentId: lastDocumentId,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>> addPatient(
    _i13.PatientModel? patientModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPatient, [patientModel]),
            returnValue:
                _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>>.value(
                  _FakeEither_2<_i12.Failure, _i13.PatientModel>(
                    this,
                    Invocation.method(#addPatient, [patientModel]),
                  ),
                ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>> updatePatient(
    String? id,
    _i13.PatientModel? patientModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [id, patientModel]),
            returnValue:
                _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>>.value(
                  _FakeEither_2<_i12.Failure, _i13.PatientModel>(
                    this,
                    Invocation.method(#updatePatient, [id, patientModel]),
                  ),
                ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, _i13.PatientModel>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, void>> deletePatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [patientId]),
            returnValue: _i9.Future<_i4.Either<_i12.Failure, void>>.value(
              _FakeEither_2<_i12.Failure, void>(
                this,
                Invocation.method(#deletePatient, [patientId]),
              ),
            ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>> searchPatients({
    String? name,
    int? minAge,
    int? maxAge,
    String? address,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPatients, [], {
              #name: name,
              #minAge: minAge,
              #maxAge: maxAge,
              #address: address,
              #gender: gender,
            }),
            returnValue: _i9.Future<
              _i4.Either<_i12.Failure, List<_i13.PatientModel>>
            >.value(
              _FakeEither_2<_i12.Failure, List<_i13.PatientModel>>(
                this,
                Invocation.method(#searchPatients, [], {
                  #name: name,
                  #minAge: minAge,
                  #maxAge: maxAge,
                  #address: address,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>>
  getPatientsByDate(
    DateTime? date, {
    _i14.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPatientsByDate,
              [date],
              {#lastDocument: lastDocument, #limit: limit},
            ),
            returnValue: _i9.Future<
              _i4.Either<_i12.Failure, List<_i13.PatientModel>>
            >.value(
              _FakeEither_2<_i12.Failure, List<_i13.PatientModel>>(
                this,
                Invocation.method(
                  #getPatientsByDate,
                  [date],
                  {#lastDocument: lastDocument, #limit: limit},
                ),
              ),
            ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, List<_i13.PatientModel>>>);

  @override
  _i9.Future<_i4.Either<_i12.Failure, int>> getPatientsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPatientsCount, []),
            returnValue: _i9.Future<_i4.Either<_i12.Failure, int>>.value(
              _FakeEither_2<_i12.Failure, int>(
                this,
                Invocation.method(#getPatientsCount, []),
              ),
            ),
          )
          as _i9.Future<_i4.Either<_i12.Failure, int>>);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i7.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_3(this, Invocation.getter(#app)),
          )
          as _i5.FirebaseApp);

  @override
  set app(_i5.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i9.Future<_i6.ActionCodeInfo>.value(
              _FakeActionCodeInfo_4(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i9.Future<_i6.ActionCodeInfo>);

  @override
  _i9.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<List<String>> fetchSignInMethodsForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSignInMethodsForEmail, [email]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<_i7.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<_i7.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Stream<_i7.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Stream<_i7.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Future<void> sendPasswordResetEmail({
    required String? email,
    _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setPersistence(_i6.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_6(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.ConfirmationResult>);

  @override
  _i9.Future<_i7.UserCredential> signInWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> signInWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i9.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i6.PhoneMultiFactorInfo? multiFactorInfo,
    required _i6.PhoneVerificationCompleted? verificationCompleted,
    required _i6.PhoneVerificationFailed? verificationFailed,
    required _i6.PhoneCodeSent? codeSent,
    required _i6.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i6.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i7.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i6.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_7(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i6.UserMetadata);

  @override
  List<_i6.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i6.UserInfo>[],
          )
          as List<_i6.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i7.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_8(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i7.MultiFactor);

  @override
  _i9.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<_i6.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i9.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_9(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i9.Future<_i6.IdTokenResult>);

  @override
  _i9.Future<_i7.UserCredential> linkWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> linkWithProvider(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithPopup(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> reauthenticateWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> linkWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> linkWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_6(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.ConfirmationResult>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendEmailVerification([
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i9.Future<_i7.User>.value(
              _FakeUser_10(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i9.Future<_i7.User>);

  @override
  _i9.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhoneNumber(
    _i6.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
