// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVZ_s8meDm3xFGfh54IkxW9G0ScMsvCM',
    appId: '1:991809114105:web:08bf9b694dfb6f1a267728',
    messagingSenderId: '991809114105',
    projectId: 'drcopilot',
    authDomain: 'drcopilot.firebaseapp.com',
    storageBucket: 'drcopilot.firebasestorage.app',
    measurementId: 'G-15ZFMXGP9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dxViBrLabhb8Ie-SE0QRTWL7pHqrKEw',
    appId: '1:991809114105:android:86655339d1f662de267728',
    messagingSenderId: '991809114105',
    projectId: 'drcopilot',
    storageBucket: 'drcopilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvkUGxy63jKSx4245xeSeB4WyT66ZQe0E',
    appId: '1:991809114105:ios:ff84bb66f8b6674c267728',
    messagingSenderId: '991809114105',
    projectId: 'drcopilot',
    storageBucket: 'drcopilot.firebasestorage.app',
    iosBundleId: 'com.alionour.drcopilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvkUGxy63jKSx4245xeSeB4WyT66ZQe0E',
    appId: '1:991809114105:ios:bf24bc30d525b4d5267728',
    messagingSenderId: '991809114105',
    projectId: 'drcopilot',
    storageBucket: 'drcopilot.firebasestorage.app',
    iosBundleId: 'com.example.drCopilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhVZ_s8meDm3xFGfh54IkxW9G0ScMsvCM',
    appId: '1:991809114105:web:b503a1abc4021649267728',
    messagingSenderId: '991809114105',
    projectId: 'drcopilot',
    authDomain: 'drcopilot.firebaseapp.com',
    storageBucket: 'drcopilot.firebasestorage.app',
    measurementId: 'G-6HQD8WGZZY',
  );

}