// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6APKuTlDJP9gGT9usJGj1Ub1Eev592PU',
    appId: '1:253522261255:web:b0c3541bbd0e1da51001a2',
    messagingSenderId: '253522261255',
    projectId: 'drcopilot-bfc9e',
    authDomain: 'drcopilot-bfc9e.firebaseapp.com',
    storageBucket: 'drcopilot-bfc9e.firebasestorage.app',
    measurementId: 'G-02M6N1VECS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDfzCa3Vu_ic4ThJRXkUMj5i327Rd5L0',
    appId: '1:253522261255:android:d7a6db0c62ce9c5c1001a2',
    messagingSenderId: '253522261255',
    projectId: 'drcopilot-bfc9e',
    storageBucket: 'drcopilot-bfc9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYHn4mg8K_47jqB4L8qaibH1jbH65AJBg',
    appId: '1:253522261255:ios:294749c166f3da071001a2',
    messagingSenderId: '253522261255',
    projectId: 'drcopilot-bfc9e',
    storageBucket: 'drcopilot-bfc9e.firebasestorage.app',
    iosBundleId: 'com.alionour.drcopilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYHn4mg8K_47jqB4L8qaibH1jbH65AJBg',
    appId: '1:253522261255:ios:f71f7a98c23548851001a2',
    messagingSenderId: '253522261255',
    projectId: 'drcopilot-bfc9e',
    storageBucket: 'drcopilot-bfc9e.firebasestorage.app',
    iosBundleId: 'com.example.drCopilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6APKuTlDJP9gGT9usJGj1Ub1Eev592PU',
    appId: '1:253522261255:web:7b3e288cbac615531001a2',
    messagingSenderId: '253522261255',
    projectId: 'drcopilot-bfc9e',
    authDomain: 'drcopilot-bfc9e.firebaseapp.com',
    storageBucket: 'drcopilot-bfc9e.firebasestorage.app',
    measurementId: 'G-SHYPP6YSQW',
  );
}
