// Mocks generated by Mockito 5.4.5 from annotations
// in dr_copilot/test/src/features/ai_voice_assistant/presentation/bloc/ai_voice_assistant_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dr_copilot/src/features/ai_voice_assistant/data/remote/speech_recognition_datasource.dart'
    as _i2;
import 'package:dr_copilot/src/features/ai_voice_assistant/data/remote/text_to_speech_datasource.dart'
    as _i4;
import 'package:dr_copilot/src/features/ai_voice_assistant/domain/services/command_parser_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SpeechRecognitionDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechRecognitionDatasource extends _i1.Mock
    implements _i2.SpeechRecognitionDatasource {
  MockSpeechRecognitionDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void startListening({required dynamic Function(String)? onResult}) =>
      super.noSuchMethod(
        Invocation.method(#startListening, [], {#onResult: onResult}),
        returnValueForMissingStub: null,
      );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [TextToSpeechDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextToSpeechDatasource extends _i1.Mock
    implements _i4.TextToSpeechDatasource {
  MockTextToSpeechDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CommandParserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandParserService extends _i1.Mock
    implements _i5.CommandParserService {
  MockCommandParserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> parseCommand(String? command) =>
      (super.noSuchMethod(
            Invocation.method(#parseCommand, [command]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
