// Mocks generated by Mockito 5.4.6 from annotations
// in dr_copilot/test/features/copilot_chat/domain/logic/function_call_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i21;

import 'package:cloud_firestore/cloud_firestore.dart' as _i12;
import 'package:dartz/dartz.dart' as _i3;
import 'package:dr_copilot/src/core/app/notifiers/owner_notifier.dart' as _i18;
import 'package:dr_copilot/src/core/error/failures.dart' as _i10;
import 'package:dr_copilot/src/features/appointments/evaluations/domain/models/evaluation_model.dart'
    as _i16;
import 'package:dr_copilot/src/features/appointments/evaluations/domain/repositories/abstract_evaluations_repository.dart'
    as _i5;
import 'package:dr_copilot/src/features/appointments/evaluations/domain/usecases/evaluations_usecase.dart'
    as _i15;
import 'package:dr_copilot/src/features/appointments/sessions/domain/models/session_model.dart'
    as _i14;
import 'package:dr_copilot/src/features/appointments/sessions/domain/repositories/abstract_sessions_repository.dart'
    as _i4;
import 'package:dr_copilot/src/features/appointments/sessions/domain/usecases/sessions_usecase.dart'
    as _i13;
import 'package:dr_copilot/src/features/auth/domain/models/clinic_model.dart'
    as _i20;
import 'package:dr_copilot/src/features/auth/domain/models/permission_enum.dart'
    as _i19;
import 'package:dr_copilot/src/features/patients/domain/models/patient_model.dart'
    as _i11;
import 'package:dr_copilot/src/features/patients/domain/repositories/abstract_patients_repository.dart'
    as _i2;
import 'package:dr_copilot/src/features/patients/domain/usecases/patients_usecase.dart'
    as _i8;
import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/src/widgets/framework.dart' as _i6;
import 'package:flutter/src/widgets/notification_listener.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAbstractPatientsRepository_0 extends _i1.SmartFake
    implements _i2.AbstractPatientsRepository {
  _FakeAbstractPatientsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbstractSessionsRepository_2 extends _i1.SmartFake
    implements _i4.AbstractSessionsRepository {
  _FakeAbstractSessionsRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbstractEvaluationsRepository_3 extends _i1.SmartFake
    implements _i5.AbstractEvaluationsRepository {
  _FakeAbstractEvaluationsRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeWidget_4 extends _i1.SmartFake implements _i6.Widget {
  _FakeWidget_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_5 extends _i1.SmartFake
    implements _i6.InheritedWidget {
  _FakeInheritedWidget_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_6 extends _i1.SmartFake
    implements _i7.DiagnosticsNode {
  _FakeDiagnosticsNode_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i7.TextTreeConfiguration? parentConfiguration,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info,
  }) => super.toString();
}

/// A class which mocks [PatientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientsUseCase extends _i1.Mock implements _i8.PatientsUseCase {
  MockPatientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AbstractPatientsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbstractPatientsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AbstractPatientsRepository);

  @override
  _i9.Future<
    _i3.Either<
      _i10.Failure,
      _i3.Tuple2<List<_i11.PatientModel>, _i12.DocumentSnapshot<Object?>?>
    >
  >
  getPatients({String? lastDocumentId, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getPatients, [], {
              #lastDocumentId: lastDocumentId,
              #limit: limit,
            }),
            returnValue:
                _i9.Future<
                  _i3.Either<
                    _i10.Failure,
                    _i3.Tuple2<
                      List<_i11.PatientModel>,
                      _i12.DocumentSnapshot<Object?>?
                    >
                  >
                >.value(
                  _FakeEither_1<
                    _i10.Failure,
                    _i3.Tuple2<
                      List<_i11.PatientModel>,
                      _i12.DocumentSnapshot<Object?>?
                    >
                  >(
                    this,
                    Invocation.method(#getPatients, [], {
                      #lastDocumentId: lastDocumentId,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i9.Future<
            _i3.Either<
              _i10.Failure,
              _i3.Tuple2<
                List<_i11.PatientModel>,
                _i12.DocumentSnapshot<Object?>?
              >
            >
          >);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>> addPatient(
    _i11.PatientModel? patientModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPatient, [patientModel]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>.value(
                  _FakeEither_1<_i10.Failure, _i11.PatientModel>(
                    this,
                    Invocation.method(#addPatient, [patientModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>> updatePatient(
    String? id,
    _i11.PatientModel? patientModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [id, patientModel]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>.value(
                  _FakeEither_1<_i10.Failure, _i11.PatientModel>(
                    this,
                    Invocation.method(#updatePatient, [id, patientModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, void>> deletePatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [patientId]),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, void>>.value(
              _FakeEither_1<_i10.Failure, void>(
                this,
                Invocation.method(#deletePatient, [patientId]),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>> searchPatients({
    String? name,
    int? minAge,
    int? maxAge,
    String? address,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPatients, [], {
              #name: name,
              #minAge: minAge,
              #maxAge: maxAge,
              #address: address,
              #gender: gender,
            }),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i11.PatientModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i11.PatientModel>>(
                    this,
                    Invocation.method(#searchPatients, [], {
                      #name: name,
                      #minAge: minAge,
                      #maxAge: maxAge,
                      #address: address,
                      #gender: gender,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>>
  getPatientsByDate(
    int? year,
    int? month, {
    _i12.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPatientsByDate,
              [year, month],
              {#lastDocument: lastDocument, #limit: limit},
            ),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i11.PatientModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i11.PatientModel>>(
                    this,
                    Invocation.method(
                      #getPatientsByDate,
                      [year, month],
                      {#lastDocument: lastDocument, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>> getPatientById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientById, [id]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>.value(
                  _FakeEither_1<_i10.Failure, _i11.PatientModel>(
                    this,
                    Invocation.method(#getPatientById, [id]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i11.PatientModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>>
  getAllPatients() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPatients, []),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i11.PatientModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i11.PatientModel>>(
                    this,
                    Invocation.method(#getAllPatients, []),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i11.PatientModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getPatientsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPatientsCount, []),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getPatientsCount, []),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);
}

/// A class which mocks [SessionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionsUseCase extends _i1.Mock implements _i13.SessionsUseCase {
  MockSessionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AbstractSessionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbstractSessionsRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AbstractSessionsRepository);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>> getSessions({
    String? lastDocumentID,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [], {
              #lastDocumentID: lastDocumentID,
              #limit: limit,
            }),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i14.SessionModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i14.SessionModel>>(
                    this,
                    Invocation.method(#getSessions, [], {
                      #lastDocumentID: lastDocumentID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>> addSession(
    _i14.SessionModel? sessionModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSession, [sessionModel]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>.value(
                  _FakeEither_1<_i10.Failure, _i14.SessionModel>(
                    this,
                    Invocation.method(#addSession, [sessionModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>> updateSession(
    String? id,
    _i14.SessionModel? sessionModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [id, sessionModel]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>.value(
                  _FakeEither_1<_i10.Failure, _i14.SessionModel>(
                    this,
                    Invocation.method(#updateSession, [id, sessionModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, void>> deleteSession(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, void>>.value(
              _FakeEither_1<_i10.Failure, void>(
                this,
                Invocation.method(#deleteSession, [id]),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>> searchSessions({
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchSessions, [], {#name: name}),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i14.SessionModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i14.SessionModel>>(
                    this,
                    Invocation.method(#searchSessions, [], {#name: name}),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>
  getSessionsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsByDate, [date]),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i14.SessionModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i14.SessionModel>>(
                    this,
                    Invocation.method(#getSessionsByDate, [date]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, String>> detectSessionType(
    String? patientId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detectSessionType, [patientId]),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, String>>.value(
              _FakeEither_1<_i10.Failure, String>(
                this,
                Invocation.method(#detectSessionType, [patientId]),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>> getSessionById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionById, [id]),
            returnValue:
                _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>.value(
                  _FakeEither_1<_i10.Failure, _i14.SessionModel>(
                    this,
                    Invocation.method(#getSessionById, [id]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i14.SessionModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>
  getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i14.SessionModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i14.SessionModel>>(
                    this,
                    Invocation.method(#getAllSessions, []),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i14.SessionModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getSessionsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsCount, []),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getSessionsCount, []),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getSessionsCountForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsCountForMonth, [], {
              #year: year,
              #month: month,
            }),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getSessionsCountForMonth, [], {
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getSessionsCountForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsCountForYear, [], {#year: year}),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getSessionsCountForYear, [], {#year: year}),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumSessionCostsForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sumSessionCostsForMonth, [], {
              #year: year,
              #month: month,
            }),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumSessionCostsForMonth, [], {
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumSessionCostsForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sumSessionCostsForYear, [], {#year: year}),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumSessionCostsForYear, [], {#year: year}),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumAllSessionCostsForUser() =>
      (super.noSuchMethod(
            Invocation.method(#sumAllSessionCostsForUser, []),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumAllSessionCostsForUser, []),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);
}

/// A class which mocks [EvaluationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluationsUseCase extends _i1.Mock
    implements _i15.EvaluationsUseCase {
  MockEvaluationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AbstractEvaluationsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbstractEvaluationsRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.AbstractEvaluationsRepository);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>
  getEvaluations({String? lastDocumentID, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluations, [], {
              #lastDocumentID: lastDocumentID,
              #limit: limit,
            }),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i16.EvaluationModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.EvaluationModel>>(
                    this,
                    Invocation.method(#getEvaluations, [], {
                      #lastDocumentID: lastDocumentID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>> addEvaluation(
    _i16.EvaluationModel? evaluationModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addEvaluation, [evaluationModel]),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, _i16.EvaluationModel>
                >.value(
                  _FakeEither_1<_i10.Failure, _i16.EvaluationModel>(
                    this,
                    Invocation.method(#addEvaluation, [evaluationModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>> updateEvaluation(
    String? id,
    _i16.EvaluationModel? evaluationModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvaluation, [id, evaluationModel]),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, _i16.EvaluationModel>
                >.value(
                  _FakeEither_1<_i10.Failure, _i16.EvaluationModel>(
                    this,
                    Invocation.method(#updateEvaluation, [id, evaluationModel]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, void>> deleteEvaluation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvaluation, [id]),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, void>>.value(
              _FakeEither_1<_i10.Failure, void>(
                this,
                Invocation.method(#deleteEvaluation, [id]),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>
  searchEvaluations({String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#searchEvaluations, [], {#name: name}),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i16.EvaluationModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.EvaluationModel>>(
                    this,
                    Invocation.method(#searchEvaluations, [], {#name: name}),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>
  getEvaluationsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationsByDate, [date]),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i16.EvaluationModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.EvaluationModel>>(
                    this,
                    Invocation.method(#getEvaluationsByDate, [date]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>> getEvaluationById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationById, [id]),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, _i16.EvaluationModel>
                >.value(
                  _FakeEither_1<_i10.Failure, _i16.EvaluationModel>(
                    this,
                    Invocation.method(#getEvaluationById, [id]),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, _i16.EvaluationModel>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>
  getAllEvaluations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvaluations, []),
            returnValue:
                _i9.Future<
                  _i3.Either<_i10.Failure, List<_i16.EvaluationModel>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.EvaluationModel>>(
                    this,
                    Invocation.method(#getAllEvaluations, []),
                  ),
                ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, List<_i16.EvaluationModel>>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getEvaluationsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationsCount, []),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getEvaluationsCount, []),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getEvaluationsCountForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationsCountForMonth, [], {
              #year: year,
              #month: month,
            }),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getEvaluationsCountForMonth, [], {
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, int>> getEvaluationsCountForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationsCountForYear, [], {#year: year}),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, int>>.value(
              _FakeEither_1<_i10.Failure, int>(
                this,
                Invocation.method(#getEvaluationsCountForYear, [], {
                  #year: year,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, int>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumEvaluationCostsForMonth({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sumEvaluationCostsForMonth, [], {
              #year: year,
              #month: month,
            }),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumEvaluationCostsForMonth, [], {
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumEvaluationCostsForYear({
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sumEvaluationCostsForYear, [], {#year: year}),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumEvaluationCostsForYear, [], {
                  #year: year,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);

  @override
  _i9.Future<_i3.Either<_i10.Failure, double>> sumAllEvaluationCostsForUser() =>
      (super.noSuchMethod(
            Invocation.method(#sumAllEvaluationCostsForUser, []),
            returnValue: _i9.Future<_i3.Either<_i10.Failure, double>>.value(
              _FakeEither_1<_i10.Failure, double>(
                this,
                Invocation.method(#sumAllEvaluationCostsForUser, []),
              ),
            ),
          )
          as _i9.Future<_i3.Either<_i10.Failure, double>>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i6.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Widget get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeWidget_4(this, Invocation.getter(#widget)),
          )
          as _i6.Widget);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  bool get debugDoingBuild =>
      (super.noSuchMethod(
            Invocation.getter(#debugDoingBuild),
            returnValue: false,
          )
          as bool);

  @override
  _i6.InheritedWidget dependOnInheritedElement(
    _i6.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #dependOnInheritedElement,
              [ancestor],
              {#aspect: aspect},
            ),
            returnValue: _FakeInheritedWidget_5(
              this,
              Invocation.method(
                #dependOnInheritedElement,
                [ancestor],
                {#aspect: aspect},
              ),
            ),
          )
          as _i6.InheritedWidget);

  @override
  void visitAncestorElements(_i6.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(#visitAncestorElements, [visitor]),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i6.ElementVisitor? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildElements, [visitor]),
    returnValueForMissingStub: null,
  );

  @override
  void dispatchNotification(_i17.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(#dispatchNotification, [notification]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.DiagnosticsNode describeElement(
    String? name, {
    _i7.DiagnosticsTreeStyle? style = _i7.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeElement, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#describeElement, [name], {#style: style}),
            ),
          )
          as _i7.DiagnosticsNode);

  @override
  _i7.DiagnosticsNode describeWidget(
    String? name, {
    _i7.DiagnosticsTreeStyle? style = _i7.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeWidget, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#describeWidget, [name], {#style: style}),
            ),
          )
          as _i7.DiagnosticsNode);

  @override
  List<_i7.DiagnosticsNode> describeMissingAncestor({
    required Type? expectedAncestorType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeMissingAncestor, [], {
              #expectedAncestorType: expectedAncestorType,
            }),
            returnValue: <_i7.DiagnosticsNode>[],
          )
          as List<_i7.DiagnosticsNode>);

  @override
  _i7.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#describeOwnershipChain, [name]),
            returnValue: _FakeDiagnosticsNode_6(
              this,
              Invocation.method(#describeOwnershipChain, [name]),
            ),
          )
          as _i7.DiagnosticsNode);
}

/// A class which mocks [OwnerNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerNotifier extends _i1.Mock implements _i18.OwnerNotifier {
  MockOwnerNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i19.AppPermission> get permissions =>
      (super.noSuchMethod(
            Invocation.getter(#permissions),
            returnValue: <_i19.AppPermission>[],
          )
          as List<_i19.AppPermission>);

  @override
  List<_i20.ClinicModel> get clinics =>
      (super.noSuchMethod(
            Invocation.getter(#clinics),
            returnValue: <_i20.ClinicModel>[],
          )
          as List<_i20.ClinicModel>);

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool hasPermission(_i19.AppPermission? permission) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [permission]),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<void> loadOwnerIdAndClinicId() =>
      (super.noSuchMethod(
            Invocation.method(#loadOwnerIdAndClinicId, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
